# Generated by Django 3.1.7 on 2021-02-19 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kazkozvuks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kazkozvuks.news')),
            ],
            options={
                'verbose_name_plural': 'news_entries',
            },
        ),
    ]
